name: github_search_app
description: SK DND ASSIGNMENT

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  cupertino_will_pop_scope: ^1.2.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.2.2
  infinite_scroll_pagination: ^4.0.0
  flutter_markdown: ^0.6.18+2
  lottie: ^2.6.0
  flutter_styled_toast: ^2.0.0

  # STATE MANAGEMENT
  provider: ^6.1.1
  flutter_hooks: ^0.20.3

  # UTIL
  intl: ^0.18.0
  single_import_generator: ^1.0.0

  # ROUTE
  go_router: ^7.0.1

  # DI
  get_it: ^7.6.4

  # NETWORK
  retrofit: ^4.0.3
  dio: ^5.4.0
  json_annotation: ^4.8.1
  http: ^1.0.0

  # LOCAL STORAGE
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  go_router_builder: ^2.3.0
  custom_lint: ^0.5.3
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/


  fonts:
    - family: pretendard_bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf

    - family: pretendard_semiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf

    - family: pretendard_regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf

    - family: pretendard_medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf

